name: easy_presentation
description: This package presents your data in the form of clean presentation view, it also supports simple text, markdown, youtube videos and tabular data form.
version: 1.0.2
homepage: https://github.com/nooralibutt/easy_presentation
repository: https://github.com/nooralibutt/easy_presentation

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.13
  youtube_player_flutter: ^8.1.2
  optimized_cached_image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: